### ISSUE TITLE
Computercraft peripheral Support

### ISSUE THREAD

**Issue by Merith-TK** [Ellemes/ExpandedStorage#77]
As it stands, CC:R is unable to access the inventory of these chests, which would make an amazing compact mass storage system possible

using SquidDev's artist program, I can create a massive storage cluster as shown here
![image](https://user-images.githubusercontent.com/10422110/151422721-1ba61691-ad6a-48f0-90fa-28fba2908310.png)

however I think its because CC:R doesnt support the inventory api that the chests by this mod uses

If its a problem with the storage api I am more than willing to move this issue over there so that the storage api can get CC integration. (have not tested with CC:T as of yet)

**Comment by NinjaPhenix** [comment]
Idealy CC:R should support the item transfer api as it would fix this however I also expose the inventory via the `InventoryProvider` interface on the block so either way would work.

Will take a look tomorrow to see if there is a feasible way to expose it on the block entity without it breaking other things / causing unexpected behaviour.

**Comment by Merith-TK** [comment]
If need be, CC:R is accepting PR's to support that inventory api

**Comment by Ellemes** [comment]
Closing in favour of new issue, sorry again for being slow to tackle issues.
