### ISSUE TITLE
Spectators cannot open Expanded Storage containers

### ISSUE THREAD

**Issue by haykam821** [Ellemes/ExpandedStorage#81]
Unlike vanilla containers, Expanded Storage containers cannot be interacted with by players in the spectator gamemode. As such, the selection box and crosshair are not visible when a spectator looks at an Expanded Storage container.

**Comment by NinjaPhenix** [comment]
Been aware of this for far too long tbh, will take look when I get back home later.

**Comment by Ellemes** [comment]
Fixed in latest alpha of container library.
