### ISSUE TITLE
expanded storage view reset/command?

### ISSUE THREAD

**Issue by N7NobodyCats** [Ellemes/ExpandedStorage#82]
is there a way to change the view of chests? im on 1.16.5 version and i wanna change how it looks  but how do i go about doing that if possible? as well as a friend who didnt get an option to choose how things were viewed or if they did they misclicked the smallest option and now everything is zoomed in for large chests

**Comment by Ellemes** [comment]
Hey you should be able to change the screen type by prssing `shift + t` with a chest open or going to the mod settings in the mod menu ( note on fabric and quilt this needs to be installed seperately ).
